In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('vienna_windows.csv')

In [4]:
df

0  0.1    1    5    10  \
0     GGGAAUGGAUCCACAUCUACGAAUUCGUACCAUAGAGAGGUUAUAC... -3.1 -3.1 -3.1  -5.8   
1     GGGAAUGGAUCCACAUCUACGAAUUCGUACCAGAGAGUGGUUAUCC... -9.2 -9.2 -9.2 -12.4   
2     GGGAAUGGAUCCACAUCUACGAAUUCGUACCAUAGAUGAGGUUAUC... -6.1 -6.1 -6.1  -8.8   
3     GGGAAUGGAUCCACAUCUACGAAUUCGUACCAUAGAGACGGUGUAU... -7.2 -7.2 -7.2  -9.9   
4     GGGAAUGGAUCCACAUCUACGAAUUCGUACCAUAGAGAGGUUAUCC... -4.3 -4.6 -4.6  -8.4   
...                                                 ...  ...  ...  ...   ...   
4931  GGGAAUGGAUCCACAUCUACGAAUUCGUACCAUAGAGAGGUCUAUC... -5.3 -5.3 -5.3  -8.0   
4932  GGGAAUGGAUCCACAUCUACGAAUUCGUACCAUGGAGGGGUUAUCC... -7.4 -7.4 -7.4 -11.0   
4933  GGGAAUGGAUCCACAUCUACGAAUUCGUACUAUAGAGAGGUUAGCC... -4.9 -4.9 -4.9  -7.6   
4934  GGGAAUGGAUCCACAUCUACGAAUUCGUACCAUAGAGACGGUUAUC... -4.8 -4.8 -4.8  -7.5   
4935  GGGAAUGGAUCCACAUCUACGAAUUCGUACCAUAGAGAGGUUAACC... -4.9 -4.9 -4.9  -7.6   

        20         40  
0    -10.5 -15.700000  
1    -15.7 -23.600000  
2    -12.0 -20.900000  
3    -12.4 -22.500000  
4    -12.0 -22.400000  
...    ...        ...  
4931 -13.0 -18.600000  
4932 -15.9 -20.100000  
4933 -10.7 -16.200001  
4934 -12.0 -18.799999  
4935 -10.7 -17.100000  

[4936 rows x 7 columns]

In [8]:
np.corrcoef(df['0.1'], df['1'])

array([[1.        , 0.98679112],
       [0.98679112, 1.        ]])

In [9]:
np.corrcoef(df['0.1'], df['5'])

array([[1.        , 0.91144181],
       [0.91144181, 1.        ]])

In [10]:
np.corrcoef(df['0.1'], df['10'])

array([[1.       , 0.8370596],
       [0.8370596, 1.       ]])

In [11]:
np.corrcoef(df['0.1'], df['20'])

array([[1.       , 0.5000281],
       [0.5000281, 1.       ]])

In [12]:
np.corrcoef(df['0.1'], df['40'])

array([[1.        , 0.46537969],
       [0.46537969, 1.        ]])

In [18]:
df.drop(['0'], axis=1).corr()

0.1         1         5        10        20        40
0.1  1.000000  0.986791  0.911442  0.837060  0.500028  0.465380
1    0.986791  1.000000  0.934132  0.870324  0.513885  0.475315
5    0.911442  0.934132  1.000000  0.909513  0.545505  0.483757
10   0.837060  0.870324  0.909513  1.000000  0.619883  0.494106
20   0.500028  0.513885  0.545505  0.619883  1.000000  0.638766
40   0.465380  0.475315  0.483757  0.494106  0.638766  1.000000